[package]
name = "dot-snippets"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.125"
serde_derive = "1.0.125"
toml = "0.5.8"
structopt = "0.3.21"
serde_json = "1.0.64"
